import { media, type MediaAsset } from "./media";

export type Service = {
  slug: string;
  title: string;
  short: string;
  intro: string[];
  includes: string[];
  closing: string;
  image: MediaAsset;
};

export const services: Service[] = [
  {
    slug: "social-media",
    title: "Social Media Management",
    short: "A consistent, recognisable presence, month after month.",
    intro: [
      "We help brands build and maintain a consistent presence across social media platforms.",
      "We don't simply fill a content calendar. We work to understand the brand, its audience, its communication style and its objectives before developing content.",
    ],
    includes: [
      "Social media strategy",
      "Content planning",
      "Creative concepts",
      "Reels",
      "Short-form videos",
      "Static creatives",
      "Carousels",
      "Stories",
      "Content writing",
      "Captions",
      "Publishing",
      "Page management",
      "Community management",
      "Content optimisation",
      "Monthly performance tracking",
      "Campaign-based content",
    ],
    closing: "Our goal is to create a social presence that feels consistent, recognisable and relevant.",
    image: media.services.social,
  },
  {
    slug: "video-production",
    title: "Video Production",
    short: "From concept to final delivery, one team.",
    intro: [
      "Video is one of the most powerful ways for a brand to communicate.",
      "Powerhouse handles video projects from concept to final delivery, so clients don't have to coordinate multiple teams for every stage of a project.",
    ],
    includes: [
      "Concept development",
      "Creative direction",
      "Script development",
      "Pre-production planning",
      "Location shoots",
      "Studio shoots",
      "Interviews",
      "Talking-head videos",
      "Product videos",
      "Brand films",
      "Corporate videos",
      "Promotional videos",
      "Social media videos",
      "Event films",
      "Reels",
      "Campaign videos",
      "YouTube content",
      "Podcast video production",
    ],
    closing: "We focus on the complete production process.",
    image: media.services.video,
  },
  {
    slug: "editing",
    title: "Editing & Post-Production",
    short: "A great shoot is only the beginning.",
    intro: [
      "Our post-production team transforms raw footage into polished content designed for its intended platform and audience.",
      "We work with footage produced by Powerhouse as well as client-provided footage, depending on the project.",
    ],
    includes: [
      "Short-form video editing",
      "Instagram Reels",
      "YouTube videos",
      "Podcast editing",
      "Promotional videos",
      "Brand films",
      "Event highlights",
      "Talking-head videos",
      "Product videos",
      "Corporate videos",
      "Trailer videos",
      "Social media cuts",
      "Motion graphics",
      "Subtitles and captions",
      "Colour correction",
      "Sound design",
      "Music integration",
      "Platform-specific versions",
    ],
    closing: "Every cut is made for the platform it will live on.",
    image: media.services.editing,
  },
  {
    slug: "photography",
    title: "Photography",
    short: "A visual library your brand can use everywhere.",
    intro: [
      "Visuals play an important role in how people perceive a brand.",
      "Powerhouse provides photography for businesses, campaigns, products, people and events.",
    ],
    includes: [
      "Brand photography",
      "Product photography",
      "Corporate photography",
      "Event photography",
      "Lifestyle photography",
      "Portraits",
      "Social media photography",
      "Campaign photography",
      "Behind-the-scenes photography",
    ],
    closing:
      "We focus not just on capturing images, but on creating a visual library that brands can use across their marketing and communication.",
    image: media.services.photography,
  },
  {
    slug: "events",
    title: "Event Management & Production",
    short: "End-to-end events, from first plan to final bow.",
    intro: [
      "Events are experiences. From planning to execution, Powerhouse provides end-to-end event solutions for brands, businesses and individuals.",
      "From intimate celebrations to corporate events and large-scale productions, our team works to ensure that every element comes together smoothly.",
    ],
    includes: [
      "Event planning",
      "Event management",
      "Event production",
      "Venue coordination",
      "Stage setup",
      "Event décor",
      "Sound and lighting",
      "DJ",
      "Emcee coordination",
      "Artist coordination",
      "Guest management",
      "Technical production",
      "Event branding",
      "Photography",
      "Videography",
      "Event coverage",
      "Highlight films",
      "On-ground coordination",
    ],
    closing: "Powerhouse is a one-stop solution for complete event management.",
    image: media.services.events,
  },
  {
    slug: "event-coverage",
    title: "Event Coverage",
    short: "An event lasts a few hours. Its content keeps working.",
    intro: [
      "An event lasts for a few hours. The content created from that event can continue working for much longer.",
      "Our coverage team captures the moments, people, energy and atmosphere of an event and turns them into content that can be used after the event.",
    ],
    includes: [
      "Event photography",
      "Event videography",
      "Reels",
      "Highlight films",
      "Same-day / fast-turnaround content where applicable",
      "Speaker coverage",
      "Guest interactions",
      "Behind-the-scenes content",
      "Brand activations",
      "Venue and décor coverage",
      "Post-event content",
    ],
    closing: "The objective is not simply to document what happened, but to capture the experience.",
    image: media.services.coverage,
  },
  {
    slug: "studio-rentals",
    title: "Studio Rentals",
    short: "A controlled space for professional content.",
    intro: [
      "Powerhouse Studios also provides a creative space for content production.",
      "The studio can be used by brands, creators, agencies and individuals who need a controlled environment for professional content production.",
    ],
    includes: [
      "Video shoots",
      "Photography",
      "Product shoots",
      "Interviews",
      "Talking-head content",
      "Podcasts",
      "Brand shoots",
      "Social media content",
      "Creator shoots",
      "Campaign production",
    ],
    closing: "Open to brands, creators, agencies and individuals.",
    image: media.services.studio,
  },
  {
    slug: "campaigns",
    title: "Brand Content & Campaigns",
    short: "One idea, carried across every format.",
    intro: [
      "Brands often need more than individual pieces of content. They need campaigns with a consistent idea, visual identity and communication direction.",
      "We bring multiple creative requirements together so that the campaign feels like one connected brand story.",
    ],
    includes: [
      "Campaign concepts",
      "Creative direction",
      "Content strategy",
      "Video production",
      "Photography",
      "Social media content",
      "Digital creatives",
      "Influencer/creator content",
      "Event integration",
      "Campaign execution",
      "Post-campaign content",
    ],
    closing: "Different formats. One connected brand story.",
    image: media.services.campaigns,
  },
];

export const enquiryTypes = [
  ...services.map((s) => s.title),
  "A complete creative partner",
  "Something else",
];
